MAIL:
  USER: ""
  PASS: ""
  HOST: ""
  PORT: ""
  WEBTEAM: "spowebteam@gmail.com"
JWT:
  EXPIRATION:
    LONG: 100
    SHORT: 1500
  PRIVATE_KEY: "pretty-big-seceret"
OTP:
  EXPIRATION: 20
  SIZE: 6
DATABASE:
  HOST: "localhost"
  PORT: "5432"
  PASSWORD: "b2Led2ke"
  USER: "admin"
APPLICATION:
  PORT: "8010"
  DBNAME: "application"
AUTH:
  PORT: "8015"
  DBNAME: "auth"
COMPANY:
  PORT: "8020"
  DBNAME: "company"
CYCLE:
  PORT: "8025"
  DBNAME: "cycle"
STUDENT:
  PORT: "8030"
  DBNAME: "student"
