MAIL:
  USER: "ias"
  PASS: ""
  HOST: "smtp.cc.iitk.ac.in"
  PORT: "25"
  WEBTEAM: "spowebteam@gmail.com"
  BATCH: 200
JWT:
  EXPIRATION:
    LONG: 100
    SHORT: 1500
  PRIVATE_KEY: "pretty-big-secret"
OTP:
  EXPIRATION: 20
  SIZE: 6
DATABASE:
  HOST: "database"
  PORT: "5432"
  PASSWORD: "b2Led2ke"
  USER: "admin"
DBNAME:
  APPLICATION: "application"
  COMPANY: "company"
  RC: "rc"
  STUDENT: "student"
  AUTH: "auth"
PORT:
  RAS: 3470
  AUTH: 3475
  STUDENT: 3480
  COMPANY: 3485
  ADMIN:
    RC: 3490
    COMPANY: 3495
    STUDENT: 3500
