MAIL:
  HOST: "patra.iitk.ac.in"
  PORT: "587"
  BATCH: 200
JWT:
  EXPIRATION:
    LONG: 5000
    SHORT: 200
PVF:
  EXPIRATION: 10080 #7days
OTP:
  EXPIRATION: 20
  SIZE: 6
DATABASE:
  HOST: "database"
  PORT: "5432"
  USER: "admin"
DBNAME:
  APPLICATION: "application"
  COMPANY: "company"
  RC: "rc"
  STUDENT: "student"
  AUTH: "auth"
PORT:
  RAS: 3470
  AUTH: 3475
  STUDENT: 3480
  COMPANY: 3485
  VERIFICATION: 3505
  ADMIN: 
    RC: 3490
    APP: 3492
    COMPANY: 3495
    STUDENT: 3500
